name: Blazing fast GitHub Pages deploy

on:
  push:
    branches:
    - master
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy site to gh-pages branch
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.FAST_GIT_PAGE_DEPLOY }}
          site-directory: web-xr.github.io
